// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnlyUgzcl_3NsRyJxaL5cbJmab_yXL42g',
    appId: '1:887221896139:web:e511bfb55caf2c6d8e6c4e',
    messagingSenderId: '887221896139',
    projectId: 'predictable-todo',
    authDomain: 'predictable-todo.firebaseapp.com',
    storageBucket: 'predictable-todo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu55kQGukmnGGehGesLmHvGhPT-SWQMII',
    appId: '1:887221896139:android:84e477c9582deaa78e6c4e',
    messagingSenderId: '887221896139',
    projectId: 'predictable-todo',
    storageBucket: 'predictable-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7dWvHU_dO4qTERQjLIFq7uxqQtwG_K0',
    appId: '1:887221896139:ios:8c3ddfd8798cf5238e6c4e',
    messagingSenderId: '887221896139',
    projectId: 'predictable-todo',
    storageBucket: 'predictable-todo.firebasestorage.app',
    iosBundleId: 'com.predictablerevenue.taskmanager.predictableTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM7dWvHU_dO4qTERQjLIFq7uxqQtwG_K0',
    appId: '1:887221896139:ios:8c3ddfd8798cf5238e6c4e',
    messagingSenderId: '887221896139',
    projectId: 'predictable-todo',
    storageBucket: 'predictable-todo.firebasestorage.app',
    iosBundleId: 'com.predictablerevenue.taskmanager.predictableTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnlyUgzcl_3NsRyJxaL5cbJmab_yXL42g',
    appId: '1:887221896139:web:f911ce5a2117c6a18e6c4e',
    messagingSenderId: '887221896139',
    projectId: 'predictable-todo',
    authDomain: 'predictable-todo.firebaseapp.com',
    storageBucket: 'predictable-todo.firebasestorage.app',
  );
}
